### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Mamingqian** [Mamingqian/MatTrip#1]
7-26 确定转刊文章的具体增加内容，开始上手 （参考TMC转刊的Difference Letter）
马鸣谦
1. 实验部分的增补  （8-16完成各自的代码， 8-20跑实验）
    - 实验部分
        - 增加2个baselines (需要有近三年发表的，深度模型 + 组合优化): DTRP的期刊版2021年的还可以，深度模型LSTPM (第十篇)，组合模型有近年的启发式算法
        - 实验部分增加1个数据集， 见第一周记录。  关于数据集的使用，有YFCC100M数据集介绍论文
        - 实验部分增加评价指标， 见第一周记录
        - 实验部分增加比较方式（场景3个，参考DTRP文章）
        - 运行时间
2. related work部分增加一个整理表: 先在Excel多设置字段，做各种分类标注，最后讨论缩减，搬到latex上

张嘉乐
3. 写作部分：
    - 第一张图重画（根据模型的修改来改图）
    - 前两个section rephrase，写作调整，建立在realted work表基础之上。
    - 增加一张示意图/ toy example
    - 实验部分对应增加分析
4. 模型实质部分
    - 2.1 实现IV.B的Feature Extraction代码
	- 2.2 IV.B 与IV.C之间 增加sequence embedding的操作，分别尝试以下两种：
		- One hot 编码
		- word2vec, 参考 https://zhuanlan.zhihu.com/p/114538417  结尾处的应用简介和参考文献
5. 跑通原文代码

7-19 第二周
张嘉乐
- [ ] 本文的程序调通
- [ ] 确定接口格式
- [ ]  2017DTRP转刊示范，分析学习一下

马鸣谦
- [ ] 实现一个简单的baseline代码   （两周）
- [ ] 处理数据集,将其转化为简单baseline的输入格式（等文本代码调通了用本文的程序进行测试）

7-12 第一周
张嘉乐：
- [x] 开共享excel扫文表
- [x] 开一个共享工作文档，包含我们的讨论记录、扫文记录、 工作计划

马鸣谦： 
- [x] 整理补充扫文表，记录一下看过的文章、问题
- [x] 开一个github共享仓库，维护一下代码的进展
- [x] 整理强相关文献（如RefA2017）
- [x] 整理刻画相关领域和方向的，用于写related work， 衬托本文的贡献。
- [x] 整理扫文结果，内容总结，见Week 1 马鸣谦内容总结

**Comment by Mamingqian** [comment]
Resolved
